name: Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4.5

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run PhpCS
      run: vendor/bin/phpcs src tests -s

    - name: Run PhpCbf
      run: vendor/bin/phpcbf src tests

    - name: Run PhpMd src dir
      run: vendor/bin/phpmd src text phpmd.xml

    - name: Run PhpMd tests dir
      run: vendor/bin/phpmd tests text phpmd.xml

    - name: Run PhpStan
      run: vendor/bin/phpstan analyse src tests --memory-limit="512M" --level=5

    - name: Set up Sqlite3 database
      run: sqlite3 test.db < setup.sql

    - name: Run unit tests
      run: vendor/bin/phpunit tests

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: |
          ./*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Prepare environment file
        run: |
          printf %s "${{ secrets.ENV_FILE }}" > .env

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Set file permissions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.WEB_USER }} ${{ secrets.DEPLOY_PATH }}
            chmod 775 ${{ secrets.DEPLOY_PATH }}
            chmod 664 ${{ secrets.DEPLOY_PATH }}huggingface.log
            chmod 664 ${{ secrets.DEPLOY_PATH }}test.db
